# Generated by Django 2.0.3 on 2018-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0008_auto_20180614_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_tag',
            field=models.CharField(choices=[('Job ad', 'Job ad'), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Acceptance', 'Acceptance'), ('Rejection', 'Rejection'), ('Offer acceptance', 'Offer acceptance')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[("Didn't apply yet", "Didn't apply yet"), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Offer accepted', 'Offer accepted')], max_length=30, null=True),
        ),
    ]
