# Generated by Django 2.0.3 on 2018-07-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0015_auto_20180705_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
