# Generated by Django 2.0.3 on 2018-07-05 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=40, null=True)),
                ('position_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Part-time intership', 'Part-time intership')], max_length=25, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=20)),
                ('on_site', models.NullBooleanField()),
                ('application_link', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[("Didn't apply yet", "Didn't apply yet"), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Offer accepted', 'Offer accepted'), ('Offer rejected', 'Offer rejected')], max_length=30, null=True)),
                ('lead', models.SmallIntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('on_site', models.NullBooleanField()),
                ('note', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_manager.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_link', models.CharField(max_length=256)),
                ('email_tag', models.CharField(blank=True, choices=[('Job ad', 'Job ad'), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Acceptance', 'Acceptance'), ('Rejection', 'Rejection'), ('Offer acceptance', 'Offer acceptance'), ('Offer rejection', 'Offer rejection')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_last_edited', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_manager.Application')),
            ],
        ),
    ]
