# Generated by Django 2.0.3 on 2018-07-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0002_auto_20180705_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_manager.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='application',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='application_manager.Application'),
            preserve_default=False,
        ),
    ]
