# Generated by Django 2.0.3 on 2018-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0006_auto_20180812_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='last_checked_date',
            field=models.DateField(null=True),
        ),
    ]
