# Generated by Django 2.0.3 on 2018-12-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0003_customcredentialsmodel_customstatemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcredentialsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customstatemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='email',
            name='application',
        ),
        migrations.RemoveField(
            model_name='email',
            name='email_address',
        ),
        migrations.AddField(
            model_name='application',
            name='email_tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CustomCredentialsModel',
        ),
        migrations.DeleteModel(
            name='CustomStateModel',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
