# Generated by Django 2.0.3 on 2018-07-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0004_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_manager.EmailAddress'),
        ),
    ]
