# Generated by Django 2.0.3 on 2018-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0005_email_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='application',
        ),
        migrations.RemoveField(
            model_name='link',
            name='application',
        ),
        migrations.RemoveField(
            model_name='note',
            name='application',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='last_checked_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
