# Generated by Django 2.0.3 on 2018-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0005_auto_20180612_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_last_edited',
            field=models.DateTimeField(),
        ),
    ]
