# Generated by Django 2.0.3 on 2018-06-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0006_auto_20180612_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Part-time intership', 'Part-time intership')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[("Didn't apply yet", "Didn't apply yet"), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=16, null=True),
        ),
    ]
