# Generated by Django 2.0.3 on 2018-06-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0007_auto_20180614_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[("Didn't apply yet", "Didn't apply yet"), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Offer accepted', 'Offer accepted')], max_length=16, null=True),
        ),
    ]
