# Generated by Django 2.0.3 on 2018-06-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0009_auto_20180617_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='position_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Part-time intership', 'Part-time intership')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[("Didn't apply yet", "Didn't apply yet"), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Offer accepted', 'Offer accepted'), ('Offer rejected', 'Offer rejected')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address_street',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_tag',
            field=models.CharField(blank=True, choices=[('Job ad', 'Job ad'), ('In progress', 'In progress'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Acceptance', 'Acceptance'), ('Rejection', 'Rejection'), ('Offer acceptance', 'Offer acceptance'), ('Offer rejection', 'Offer rejection')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
